# Generated by Django 5.1.2 on 2024-12-03 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0003_userkakao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='kakaoid',
        ),
    ]
