# Generated by Django 5.1.2 on 2024-12-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0004_remove_user_fullname_remove_user_kakaoid'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserKeyInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('binanceId', models.CharField(db_column='binanceId', max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('isKeyActive', models.BooleanField(db_column='isKeyActive')),
                ('binanceApiKey', models.CharField(db_column='binanceApiKey', max_length=255)),
                ('binanceSecretKey', models.CharField(db_column='binanceSecretKey', max_length=255)),
            ],
            options={
                'db_table': 'UserKeyInfo',
                'managed': False,
            },
        ),
    ]
