# Generated by Django 5.1.2 on 2025-02-11 13:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("kakao_id", models.BigIntegerField(db_column="kakaoId", unique=True)),
                (
                    "account_email",
                    models.EmailField(db_column="accountEmail", max_length=255),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "phone_number",
                    models.CharField(db_column="phoneNumber", max_length=255),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_column="createdAt"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_column="deletedAt", null=True),
                ),
            ],
            options={
                "db_table": "User",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserKeyInfo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("binance_id", models.CharField(db_column="binanceId", max_length=255)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_column="createdAt", default=django.utils.timezone.now
                    ),
                ),
                (
                    "is_connected",
                    models.BooleanField(db_column="isConnected", default=False),
                ),
                (
                    "is_key_active",
                    models.BooleanField(db_column="isKeyActive", default=True),
                ),
                (
                    "binance_api_key",
                    models.CharField(db_column="binanceApiKey", max_length=255),
                ),
                (
                    "binance_secret_key",
                    models.CharField(db_column="binanceSecretKey", max_length=255),
                ),
            ],
            options={
                "db_table": "UserKeyInfo",
                "managed": False,
            },
        ),
    ]
